import { db } from '$lib/server/db';
import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { sql } from 'drizzle-orm';
import { frigateInstances } from '$lib/utils';

export const GET: RequestHandler = async ({ locals }) => {
	// Ensure user is authenticated
	if (!locals.user) {
		throw error(401, 'Unauthorized');
	}

	try {
		const result = [
			{
				id: 'GATE_CAMERA_DETAILS_PARKING_GATE_11PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_PARKING_GATE_11PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_PARKING_GATE_22PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_PARKING_GATE_22PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_1_IN3ENTERANCE',
				name: 'GATE_CAMERA_DETAILS_GATE_1_IN3ENTERANCE',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_1_OUT4EXIT_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_1_OUT4EXIT_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_4_IN5QUEUE_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_4_IN5QUEUE_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_4_OUT6ROAD_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_4_OUT6ROAD_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_5_OUT7PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_5_OUT7PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_6_IN8PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_6_IN8PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_6_OUT9ROAD_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_6_OUT9ROAD_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_8_IN10BLURR',
				name: 'GATE_CAMERA_DETAILS_GATE_8_IN10BLURR',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_9_IN11ROAD_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_9_IN11ROAD_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_10_OUT12ROAD_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_10_OUT12ROAD_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_11_IN13PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_11_IN13PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_13_IN14PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_13_IN14PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_13_OUT15BLURR',
				name: 'GATE_CAMERA_DETAILS_GATE_13_OUT15BLURR',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_14_IN16ENTRANCE_CHECKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_14_IN16ENTRANCE_CHECKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_14_OUT17QUEUE_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_14_OUT17QUEUE_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_15_OUT18BLURR',
				name: 'GATE_CAMERA_DETAILS_GATE_15_OUT18BLURR',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_GATE_16_OUT19ROAD_BUILDING_VIEW',
				name: 'GATE_CAMERA_DETAILS_GATE_16_OUT19ROAD_BUILDING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_MCC_GATE20PARKING_VIEW',
				name: 'GATE_CAMERA_DETAILS_MCC_GATE20PARKING_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_MCC_GATE21ROAD_VIEW',
				name: 'GATE_CAMERA_DETAILS_MCC_GATE21ROAD_VIEW',
				url: ''
			},
			{
				id: 'GATE_CAMERA_DETAILS_AG_RAM_SING_GATE1',
				name: 'GATE_CAMERA_DETAILS_AG_RAM_SING_GATE1',
				url: ''
			},
			{ id: 'GATE_CAMERA_DETAILS_FIRE_GATE2', name: 'GATE_CAMERA_DETAILS_FIRE_GATE2', url: '' },
			{
				id: 'GATE_CAMERA_DETAILS_AB_LEVEL_0_CAMERAS_GATE_81',
				name: 'GATE_CAMERA_DETAILS_AB_LEVEL_0_CAMERAS_GATE_81',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_C_STAND_UPPER_ENTRY1',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_C_STAND_UPPER_ENTRY1',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_C_STAND_LOWER_ENTRY2',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_C_STAND_LOWER_ENTRY2',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_D_STAND_UPPER_ENTRY3',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_D_STAND_UPPER_ENTRY3',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_D_STAND_LOWER_ENTRY4',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_D_STAND_LOWER_ENTRY4',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_E_STAND_UPPER_ENTRY5',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_E_STAND_UPPER_ENTRY5',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_E_STAND_LOWER_ENTRY6',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_E_STAND_LOWER_ENTRY6',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_F_STAND_UPPER_ENTRY7',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_F_STAND_UPPER_ENTRY7',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_F_STAND_LOWER_ENTRY8',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_F_STAND_LOWER_ENTRY8',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_G_STAND_UPPER_ENTRY9',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_G_STAND_UPPER_ENTRY9',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_G_STAND_LOWER_ENTRY10',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_G_STAND_LOWER_ENTRY10',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_H_STAND_UPPER_ENTRY11',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_H_STAND_UPPER_ENTRY11',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_H_STAND_LOWER_ENTRY12',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_H_STAND_LOWER_ENTRY12',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_I_STAND_UPPER_ENTRY13',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_I_STAND_UPPER_ENTRY13',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_I_STAND_LOWER_ENTRY14',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_I_STAND_LOWER_ENTRY14',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_J_STAND_UPPER_ENTRY15',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_J_STAND_UPPER_ENTRY15',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_J_STAND_LOWER_ENTRY16',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_J_STAND_LOWER_ENTRY16',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_K_STAND_UPPER_ENTRY17',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_K_STAND_UPPER_ENTRY17',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_K_STAND_LOWER_ENTRY18',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_K_STAND_LOWER_ENTRY18',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_2_STAIR_CASE_1',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_2_STAIR_CASE_1',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_2_STAIR_CASE_2',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_2_STAIR_CASE_2',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_2_STAIR_CASE_3',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_2_STAIR_CASE_3',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_3_STAIR_CASE_ENTRY',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_3_STAIR_CASE_ENTRY',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LIFT_LOBBY_LEVEL_2',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LIFT_LOBBY_LEVEL_2',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_3_SERVICE_LIFT_ENTRY',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_3_SERVICE_LIFT_ENTRY',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_3_LIFT_ENTRY',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_KMK_STAND_LEVEL_3_LIFT_ENTRY',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_INNER_PHERIPERAL_CAMERASMAC_B_ENTRY_2',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_INNER_PHERIPERAL_CAMERASMAC_B_ENTRY_2',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_INNER_PHERIPERAL_CAMERASB_GROUND_ENTRY_1',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_INNER_PHERIPERAL_CAMERASB_GROUND_ENTRY_1',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_A_B_LEVEL_0_CAMERASVIP_STAND_ENTRY',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_A_B_LEVEL_0_CAMERASVIP_STAND_ENTRY',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_A_B_LEVEL_0_CAMERASACADEMY_ENTRY',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_A_B_LEVEL_0_CAMERASACADEMY_ENTRY',
				url: ''
			},
			{
				id: 'STAND_ENTRY_EXIT_CAMERA_DETAI_H_LOWER_PLAYER_ENTRY1',
				name: 'STAND_ENTRY_EXIT_CAMERA_DETAI_H_LOWER_PLAYER_ENTRY1',
				url: ''
			},
			{ id: 'CONCOURSE_INNER_PHERIPAL_CAMERAS', name: 'CONCOURSE_INNER_PHERIPAL_CAMERAS', url: '' },
			{ id: 'CONCOURSE_PATTABIRAMAN_GATE1', name: 'CONCOURSE_PATTABIRAMAN_GATE1', url: '' },
			{ id: 'CONCOURSE_H_STAND_PASSAGE2', name: 'CONCOURSE_H_STAND_PASSAGE2', url: '' },
			{ id: 'CONCOURSE_I_H_PASSAGE3', name: 'CONCOURSE_I_H_PASSAGE3', url: '' },
			{ id: 'CONCOURSE_I_J_PASSAGE4', name: 'CONCOURSE_I_J_PASSAGE4', url: '' },
			{ id: 'CONCOURSE_F_STAND_PASSAGE5', name: 'CONCOURSE_F_STAND_PASSAGE5', url: '' },
			{ id: 'CONCOURSE_PUMP_ROOM6', name: 'CONCOURSE_PUMP_ROOM6', url: '' },
			{ id: 'CONCOURSE_MEDIA_ENTRY7', name: 'CONCOURSE_MEDIA_ENTRY7', url: '' },
			{ id: 'CONCOURSE_E_CORRIDOR8', name: 'CONCOURSE_E_CORRIDOR8', url: '' },
			{ id: 'CONCOURSE_VOC_CORRIDOR9', name: 'CONCOURSE_VOC_CORRIDOR9', url: '' },
			{ id: 'CONCOURSE_CD_PHERIPERAL10', name: 'CONCOURSE_CD_PHERIPERAL10', url: '' },
			{ id: 'CONCOURSE_CD_PHERIPERAL11', name: 'CONCOURSE_CD_PHERIPERAL11', url: '' },
			{ id: 'CONCOURSE_CD_PHERIPERAL12', name: 'CONCOURSE_CD_PHERIPERAL12', url: '' },
			{ id: 'CONCOURSE_STAND_I_1PASSAGE_1', name: 'CONCOURSE_STAND_I_1PASSAGE_1', url: '' },
			{ id: 'CONCOURSE_STAND_I_2PASSAGE_2', name: 'CONCOURSE_STAND_I_2PASSAGE_2', url: '' },
			{ id: 'CONCOURSE_STAND_K1PASSAGE_1', name: 'CONCOURSE_STAND_K1PASSAGE_1', url: '' },
			{ id: 'CONCOURSE_STAND_K2PASSAGE_2', name: 'CONCOURSE_STAND_K2PASSAGE_2', url: '' },
			{ id: 'CONCOURSE_A_B_LEVEL_0_CAMERAS', name: 'CONCOURSE_A_B_LEVEL_0_CAMERAS', url: '' },
			{ id: 'CONCOURSE_C_STAND_STORE2', name: 'CONCOURSE_C_STAND_STORE2', url: '' },
			{ id: 'CONCOURSE_J_STAND_3', name: 'CONCOURSE_J_STAND_3', url: '' },
			{ id: 'CONCOURSE_MCC_OUT_PASSAGE6', name: 'CONCOURSE_MCC_OUT_PASSAGE6', url: '' },
			{ id: 'CONCOURSE_BEHIND_PUMP_ROOM7', name: 'CONCOURSE_BEHIND_PUMP_ROOM7', url: '' },
			{
				id: 'CONCOURSE_KMK_STANDS_CONCOURSE_CAMERAS2',
				name: 'CONCOURSE_KMK_STANDS_CONCOURSE_CAMERAS2',
				url: ''
			},
			{
				id: 'FOOD_STALL_STAND_C_1LOWER_PASSAGE_1',
				name: 'FOOD_STALL_STAND_C_1LOWER_PASSAGE_1',
				url: ''
			},
			{
				id: 'FOOD_STALL_STAND_C_2LOWER_PASSAGE_2',
				name: 'FOOD_STALL_STAND_C_2LOWER_PASSAGE_2',
				url: ''
			},
			{ id: 'FOOD_STALL_STAND_C_32_F_DINING', name: 'FOOD_STALL_STAND_C_32_F_DINING', url: '' },
			{ id: 'FOOD_STALL_STAND_D_1PASSAGE_1', name: 'FOOD_STALL_STAND_D_1PASSAGE_1', url: '' },
			{ id: 'FOOD_STALL_STAND_D_2PASSAGE_2', name: 'FOOD_STALL_STAND_D_2PASSAGE_2', url: '' },
			{ id: 'FOOD_STALL_STAND_D_32_F_DINING', name: 'FOOD_STALL_STAND_D_32_F_DINING', url: '' },
			{ id: 'FOOD_STALL_STAND_E_1PASSAGE_1', name: 'FOOD_STALL_STAND_E_1PASSAGE_1', url: '' },
			{ id: 'FOOD_STALL_STAND_E_2PASSAGE_1', name: 'FOOD_STALL_STAND_E_2PASSAGE_1', url: '' },
			{ id: 'FOOD_STALL_STAND_E_32_F_DINING', name: 'FOOD_STALL_STAND_E_32_F_DINING', url: '' },
			{
				id: 'FOOD_STALL_STAND_E_42_F_LIFT_BUT_FOOD_AREA',
				name: 'FOOD_STALL_STAND_E_42_F_LIFT_BUT_FOOD_AREA',
				url: ''
			},
			{ id: 'FOOD_STALL_STAND_F_1PASSAGE_1', name: 'FOOD_STALL_STAND_F_1PASSAGE_1', url: '' },
			{
				id: 'FOOD_STALL_STAND_F_2LEVEL_3_DINNING',
				name: 'FOOD_STALL_STAND_F_2LEVEL_3_DINNING',
				url: ''
			},
			{
				id: 'FOOD_STALL_STAND_F_3LEVEL_3_DINNING',
				name: 'FOOD_STALL_STAND_F_3LEVEL_3_DINNING',
				url: ''
			},
			{
				id: 'FOOD_STALL_STAND_F_4LEVEL_3_DINNING',
				name: 'FOOD_STALL_STAND_F_4LEVEL_3_DINNING',
				url: ''
			},
			{
				id: 'FOOD_STALL_STAND_F_5LEVEL_3_DINNING',
				name: 'FOOD_STALL_STAND_F_5LEVEL_3_DINNING',
				url: ''
			},
			{ id: 'FOOD_STALL_E_2_F_STEPS1', name: 'FOOD_STALL_E_2_F_STEPS1', url: '' },
			{ id: 'FOOD_STALL_STAND_J1PASSAGE_2', name: 'FOOD_STALL_STAND_J1PASSAGE_2', url: '' },
			{ id: 'FOOD_STALL_BCR_1LAPTOP_STORAGE', name: 'FOOD_STALL_BCR_1LAPTOP_STORAGE', url: '' },
			{ id: 'FOOD_STALL_BCR_2LAPTOP_STORAGE', name: 'FOOD_STALL_BCR_2LAPTOP_STORAGE', url: '' },
			{ id: 'FOOD_STALL_STAND_H_12F_GALLERY', name: 'FOOD_STALL_STAND_H_12F_GALLERY', url: '' },
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_1LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_1LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_2LEVEL_2_UPPER_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_2LEVEL_2_UPPER_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_3LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_3LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_4LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_4LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_5LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_5LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_6LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_6LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_7LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_7LEVEL_2_UPPER_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_1LEVEL_5_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_1LEVEL_5_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_2LEVEL_5_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_KMK_GALLERY_CAMERA_2LEVEL_5_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_C_1GALLERY_PTZ_RIGHT_VIEW_CAMERA',
				name: 'GALLERY_CAMERA_STAND_C_1GALLERY_PTZ_RIGHT_VIEW_CAMERA',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_C_2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_C_2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_C_3UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_C_3UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_D1GALLERY_PTZ_LEFT_VIEW_CAMERA',
				name: 'GALLERY_CAMERA_STAND_D1GALLERY_PTZ_LEFT_VIEW_CAMERA',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_D2UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_D2UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_D3UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_D3UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_E1GALLERY_PTZ_RIGHT_VIEW_CAMERA',
				name: 'GALLERY_CAMERA_STAND_E1GALLERY_PTZ_RIGHT_VIEW_CAMERA',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_E2UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_E2UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_E3UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_E3UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_F1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_F1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_F2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_F2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_G1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_G1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_G2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_G2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_H12F_GALLERY_RIGHT_VIEW',
				name: 'GALLERY_CAMERA_STAND_H12F_GALLERY_RIGHT_VIEW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_H2LOWER_LEFT_VIEW',
				name: 'GALLERY_CAMERA_STAND_H2LOWER_LEFT_VIEW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_H3UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_H3UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_H4UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_H4UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_I1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_I1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_I2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_I2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_I3UPPER_RIGHT_VIEW',
				name: 'GALLERY_CAMERA_STAND_I3UPPER_RIGHT_VIEW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_J1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_J1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_J2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_J2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_J3LOWER_PTZ_RIGHT_VIEW',
				name: 'GALLERY_CAMERA_STAND_J3LOWER_PTZ_RIGHT_VIEW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_K1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_K1UPPER_DOWN_TO_UP_LEFT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_K2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				name: 'GALLERY_CAMERA_STAND_K2UPPER_DOWN_TO_UP_RIGHT_SIDE_SHOW',
				url: ''
			},
			{
				id: 'GALLERY_CAMERA_STAND_K3LOWER_PTZ_LEFT_VIEW',
				name: 'GALLERY_CAMERA_STAND_K3LOWER_PTZ_LEFT_VIEW',
				url: ''
			},
			{ id: 'GALLERY_CAMERA_STAND_K4', name: 'GALLERY_CAMERA_STAND_K4', url: '' },
			{ id: 'EXTERNAL_CAMERAS_BHURAI_11', name: 'EXTERNAL_CAMERAS_BHURAI_11', url: '' },
			{ id: 'EXTERNAL_CAMERAS_BHURAI_22', name: 'EXTERNAL_CAMERAS_BHURAI_22', url: '' },
			{
				id: 'EXTERNAL_CAMERAS_MOUNT_ROAD_SIGNAL3',
				name: 'EXTERNAL_CAMERAS_MOUNT_ROAD_SIGNAL3',
				url: ''
			},
			{ id: 'EXTERNAL_CAMERAS_GH_BUSTAND4', name: 'EXTERNAL_CAMERAS_GH_BUSTAND4', url: '' },
			{ id: 'EXTERNAL_CAMERAS_D1_BUS_STAND5', name: 'EXTERNAL_CAMERAS_D1_BUS_STAND5', url: '' },
			{ id: 'EXTERNAL_CAMERAS_D1_BUS_STAND6', name: 'EXTERNAL_CAMERAS_D1_BUS_STAND6', url: '' },
			{ id: 'EXTERNAL_CAMERAS_D1_JUNCTION7', name: 'EXTERNAL_CAMERAS_D1_JUNCTION7', url: '' },
			{ id: 'EXTERNAL_CAMERAS_D1_STATION8', name: 'EXTERNAL_CAMERAS_D1_STATION8', url: '' },
			{
				id: 'EXTERNAL_CAMERAS_TRIPLICANCE_HIGH_ROAD9',
				name: 'EXTERNAL_CAMERAS_TRIPLICANCE_HIGH_ROAD9',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_LABOUR_STATUE_SIGNAL10',
				name: 'EXTERNAL_CAMERAS_LABOUR_STATUE_SIGNAL10',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_KALAIVANAR_ARANGAM11',
				name: 'EXTERNAL_CAMERAS_KALAIVANAR_ARANGAM11',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_KALAIVANAR_ARANGAM12',
				name: 'EXTERNAL_CAMERAS_KALAIVANAR_ARANGAM12',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_WALAJA_ROAD_GATE_1113',
				name: 'EXTERNAL_CAMERAS_WALAJA_ROAD_GATE_1113',
				url: ''
			},
			{ id: 'EXTERNAL_CAMERAS_GH_BUSTAND_214', name: 'EXTERNAL_CAMERAS_GH_BUSTAND_214', url: '' },
			{ id: 'EXTERNAL_CAMERAS_ESTATE_METRO15', name: 'EXTERNAL_CAMERAS_ESTATE_METRO15', url: '' },
			{
				id: 'EXTERNAL_CAMERAS_HOSPITAL_ENTRY16',
				name: 'EXTERNAL_CAMERAS_HOSPITAL_ENTRY16',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_PERIYAR_STATUE17',
				name: 'EXTERNAL_CAMERAS_PERIYAR_STATUE17',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_SIVANANDHA_SALAI_118',
				name: 'EXTERNAL_CAMERAS_SIVANANDHA_SALAI_118',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_VICTORIA_ROAD_JUNCTION19',
				name: 'EXTERNAL_CAMERAS_VICTORIA_ROAD_JUNCTION19',
				url: ''
			},
			{ id: 'EXTERNAL_CAMERAS_PYCROFTS_ROAD20', name: 'EXTERNAL_CAMERAS_PYCROFTS_ROAD20', url: '' },
			{ id: 'EXTERNAL_CAMERAS_PYCROFTS_ROAD21', name: 'EXTERNAL_CAMERAS_PYCROFTS_ROAD21', url: '' },
			{ id: 'EXTERNAL_CAMERAS_BARATHI_SALAI22', name: 'EXTERNAL_CAMERAS_BARATHI_SALAI22', url: '' },
			{ id: 'EXTERNAL_CAMERAS_PYCROFTS_ROAD23', name: 'EXTERNAL_CAMERAS_PYCROFTS_ROAD23', url: '' },
			{ id: 'EXTERNAL_CAMERAS_BELLS_ROAD24', name: 'EXTERNAL_CAMERAS_BELLS_ROAD24', url: '' },
			{
				id: 'EXTERNAL_CAMERAS_LIBRARY_ENTRANCEMLA25',
				name: 'EXTERNAL_CAMERAS_LIBRARY_ENTRANCEMLA25',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_MLA_HOSTEL_ENTRY26',
				name: 'EXTERNAL_CAMERAS_MLA_HOSTEL_ENTRY26',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_SIVANANDHA_SALAI27',
				name: 'EXTERNAL_CAMERAS_SIVANANDHA_SALAI27',
				url: ''
			},
			{ id: 'EXTERNAL_CAMERAS_L_T_GATE28', name: 'EXTERNAL_CAMERAS_L_T_GATE28', url: '' },
			{
				id: 'EXTERNAL_CAMERAS_SIVANANDHA_SALAI_29',
				name: 'EXTERNAL_CAMERAS_SIVANANDHA_SALAI_29',
				url: ''
			},
			{ id: 'EXTERNAL_CAMERAS_MLA_HOSTEL30', name: 'EXTERNAL_CAMERAS_MLA_HOSTEL30', url: '' },
			{
				id: 'EXTERNAL_CAMERAS_MLA_HOSTEL_EXIT31',
				name: 'EXTERNAL_CAMERAS_MLA_HOSTEL_EXIT31',
				url: ''
			},
			{
				id: 'EXTERNAL_CAMERAS_LABOUR_STATUE_SIGNAL32',
				name: 'EXTERNAL_CAMERAS_LABOUR_STATUE_SIGNAL32',
				url: ''
			},
			{
				id: 'ROAD_SIDE_CAMERA_LOCK_NAGAR_JUNCTION1',
				name: 'ROAD_SIDE_CAMERA_LOCK_NAGAR_JUNCTION1',
				url: ''
			},
			{
				id: 'ROAD_SIDE_CAMERA_LOCK_NAGAR_ENTRY2',
				name: 'ROAD_SIDE_CAMERA_LOCK_NAGAR_ENTRY2',
				url: ''
			},
			{ id: 'ROAD_SIDE_CAMERA_PARKING_ROAD3', name: 'ROAD_SIDE_CAMERA_PARKING_ROAD3', url: '' },
			{ id: 'ROAD_SIDE_CAMERA_PARKING_ROAD4', name: 'ROAD_SIDE_CAMERA_PARKING_ROAD4', url: '' },
			{
				id: 'ROAD_SIDE_CAMERA_DD_SIVANANDHA_SALAI5',
				name: 'ROAD_SIDE_CAMERA_DD_SIVANANDHA_SALAI5',
				url: ''
			},
			{
				id: 'ROAD_SIDE_CAMERA_DD_SIVANANDHA_SALAI6',
				name: 'ROAD_SIDE_CAMERA_DD_SIVANANDHA_SALAI6',
				url: ''
			},
			{
				id: 'ROAD_SIDE_CAMERA_DD_SIVANANDHA_SALAI7',
				name: 'ROAD_SIDE_CAMERA_DD_SIVANANDHA_SALAI7',
				url: ''
			},
			{ id: 'OFFICE_ROOMS_CCTV_CONTROL_ROOM1', name: 'OFFICE_ROOMS_CCTV_CONTROL_ROOM1', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_0_LIFT2', name: 'OFFICE_ROOMS_J_LEVEL_0_LIFT2', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_0_LIFT3', name: 'OFFICE_ROOMS_J_LEVEL_0_LIFT3', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_1_LIFT4', name: 'OFFICE_ROOMS_J_LEVEL_1_LIFT4', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_15', name: 'OFFICE_ROOMS_J_LEVEL_15', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_16', name: 'OFFICE_ROOMS_J_LEVEL_16', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_3_LIFT7', name: 'OFFICE_ROOMS_J_LEVEL_3_LIFT7', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_38', name: 'OFFICE_ROOMS_J_LEVEL_38', url: '' },
			{ id: 'OFFICE_ROOMS_CCTV_CONTROL_ROOM9', name: 'OFFICE_ROOMS_CCTV_CONTROL_ROOM9', url: '' },
			{ id: 'OFFICE_ROOMS_J_LEVEL_0_OFFICE10', name: 'OFFICE_ROOMS_J_LEVEL_0_OFFICE10', url: '' },
			{ id: 'OFFICE_ROOMS_C_VENUE_OFFICE11', name: 'OFFICE_ROOMS_C_VENUE_OFFICE11', url: '' },
			{ id: 'OFFICE_ROOMS_SECURITY_ROOM12', name: 'OFFICE_ROOMS_SECURITY_ROOM12', url: '' },
			{
				id: 'OFFICE_ROOMS_KMK_STAND_LEVEL_3_LIFT_ENTRY_13',
				name: 'OFFICE_ROOMS_KMK_STAND_LEVEL_3_LIFT_ENTRY_13',
				url: ''
			},
			{ id: 'OFFICE_ROOMS_B_C_ENTERANCE1', name: 'OFFICE_ROOMS_B_C_ENTERANCE1', url: '' },
			{ id: 'STEPS_AB_LEVEL_0_CAMERAS', name: 'STEPS_AB_LEVEL_0_CAMERAS', url: '' },
			{ id: 'STEPS_VIP_STAND_STAIR_CASE_EB10', name: 'STEPS_VIP_STAND_STAIR_CASE_EB10', url: '' },
			{ id: 'STEPS_VIP_STAND_STAIR_CASE20', name: 'STEPS_VIP_STAND_STAIR_CASE20', url: '' },
			{ id: 'STEPS_A_STAND_STAIRCASE_130', name: 'STEPS_A_STAND_STAIRCASE_130', url: '' },
			{ id: 'STEPS_A_STAND_STAIRCASE_40', name: 'STEPS_A_STAND_STAIRCASE_40', url: '' },
			{ id: 'STEPS_VIPSTAIRCASE_GF_A50', name: 'STEPS_VIPSTAIRCASE_GF_A50', url: '' },
			{
				id: 'STEPS_B_STAND_STAIR_CASE_OF_EM_EXIT60',
				name: 'STEPS_B_STAND_STAIR_CASE_OF_EM_EXIT60',
				url: ''
			},
			{ id: 'STEPS_STAIR_CASE70', name: 'STEPS_STAIR_CASE70', url: '' },
			{ id: 'STEPS_K_LEVEL_1_STAIR_CASE80', name: 'STEPS_K_LEVEL_1_STAIR_CASE80', url: '' },
			{ id: 'STEPS_K_LEVEL_2_STAIR_CASE90', name: 'STEPS_K_LEVEL_2_STAIR_CASE90', url: '' },
			{ id: 'STEPS_K_LEVEL_3_STAIR_CASE100', name: 'STEPS_K_LEVEL_3_STAIR_CASE100', url: '' },
			{ id: 'STEPS_C_2_F_STEPS110', name: 'STEPS_C_2_F_STEPS110', url: '' },
			{ id: 'STEPS_C_2_F_STEPS120', name: 'STEPS_C_2_F_STEPS120', url: '' },
			{ id: 'STEPS_D_2_F_STEPS130', name: 'STEPS_D_2_F_STEPS130', url: '' },
			{ id: 'STEPS_D_2_F_STEPS140', name: 'STEPS_D_2_F_STEPS140', url: '' },
			{ id: 'STEPS_E_2_F_STEPS150', name: 'STEPS_E_2_F_STEPS150', url: '' },
			{ id: 'KMK_BOX_KMK_STAND_BOXES', name: 'KMK_BOX_KMK_STAND_BOXES', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_110', name: 'KMK_BOX_LEVEL_3_AC_BOX_110', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_220', name: 'KMK_BOX_LEVEL_3_AC_BOX_220', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_330', name: 'KMK_BOX_LEVEL_3_AC_BOX_330', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_440', name: 'KMK_BOX_LEVEL_3_AC_BOX_440', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_550', name: 'KMK_BOX_LEVEL_3_AC_BOX_550', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_660', name: 'KMK_BOX_LEVEL_3_AC_BOX_660', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_770', name: 'KMK_BOX_LEVEL_3_AC_BOX_770', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_880', name: 'KMK_BOX_LEVEL_3_AC_BOX_880', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_990', name: 'KMK_BOX_LEVEL_3_AC_BOX_990', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_10100', name: 'KMK_BOX_LEVEL_3_AC_BOX_10100', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_11110', name: 'KMK_BOX_LEVEL_3_AC_BOX_11110', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_12120', name: 'KMK_BOX_LEVEL_3_AC_BOX_12120', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_13130', name: 'KMK_BOX_LEVEL_3_AC_BOX_13130', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_14140', name: 'KMK_BOX_LEVEL_3_AC_BOX_14140', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_15150', name: 'KMK_BOX_LEVEL_3_AC_BOX_15150', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_16160', name: 'KMK_BOX_LEVEL_3_AC_BOX_16160', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_17170', name: 'KMK_BOX_LEVEL_3_AC_BOX_17170', url: '' },
			{ id: 'KMK_BOX_LEVEL_3_AC_BOX_18180', name: 'KMK_BOX_LEVEL_3_AC_BOX_18180', url: '' },
			{
				id: 'HOSPITALITY_KMK_STAND_HOSPITALITY',
				name: 'HOSPITALITY_KMK_STAND_HOSPITALITY',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_110',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_110',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_220',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_220',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_330',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_330',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_440',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_440',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_550',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_550',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_660',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_660',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_770',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_770',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_3_HOSPITALITY_880',
				name: 'HOSPITALITY_LEVEL_3_HOSPITALITY_880',
				url: ''
			},
			{
				id: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY90',
				name: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY90',
				url: ''
			},
			{
				id: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY100',
				name: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY100',
				url: ''
			},
			{
				id: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY110',
				name: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY110',
				url: ''
			},
			{
				id: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY120',
				name: 'HOSPITALITY_G_LEVEL_3_HOSPITALITY120',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_110',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_110',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_220',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_220',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_330',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_330',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_440',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_440',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_550',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_550',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_660',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_660',
				url: ''
			},
			{
				id: 'HOSPITALITY_LEVEL_2_HOSPITALITY_770',
				name: 'HOSPITALITY_LEVEL_2_HOSPITALITY_770',
				url: ''
			},
			{
				id: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_110',
				name: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_110',
				url: ''
			},
			{
				id: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_220',
				name: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_220',
				url: ''
			},
			{
				id: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_330',
				name: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_330',
				url: ''
			},
			{
				id: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_440',
				name: 'HOSPITALITY_F_LEVEL_3_HOSPITALITY_440',
				url: ''
			},
			{ id: 'MEDIA_ROOMS_PRESS_CONFERENCE1', name: 'MEDIA_ROOMS_PRESS_CONFERENCE1', url: '' },
			{ id: 'MEDIA_ROOMS_PRESS_CONFERENCE2', name: 'MEDIA_ROOMS_PRESS_CONFERENCE2', url: '' },
			{ id: 'MEDIA_ROOMS_F_MEDIA3', name: 'MEDIA_ROOMS_F_MEDIA3', url: '' },
			{ id: 'MEDIA_ROOMS_F_MEDIA4', name: 'MEDIA_ROOMS_F_MEDIA4', url: '' },
			{ id: 'MEDIA_ROOMS_F_MEDIA5', name: 'MEDIA_ROOMS_F_MEDIA5', url: '' },
			{ id: 'MEDIA_ROOMS_MARKER_AREA6', name: 'MEDIA_ROOMS_MARKER_AREA6', url: '' },
			{ id: 'LIFTS_KMK_STAND_LIFTS', name: 'LIFTS_KMK_STAND_LIFTS', url: '' },
			{ id: 'LIFTS_LEVEL_2_SERVICE_LIFT1', name: 'LIFTS_LEVEL_2_SERVICE_LIFT1', url: '' },
			{ id: 'LIFTS_A_B_LEVEL_0_CAMERAS', name: 'LIFTS_A_B_LEVEL_0_CAMERAS', url: '' },
			{ id: 'LIFTS_SERVICELIFT_GF1', name: 'LIFTS_SERVICELIFT_GF1', url: '' },
			{ id: 'LIFTS_VIP_STAND_LIFT2', name: 'LIFTS_VIP_STAND_LIFT2', url: '' },
			{
				id: 'LIFTS_KMK_STAND_LEVEL_2_LIFT_ENTRY',
				name: 'LIFTS_KMK_STAND_LEVEL_2_LIFT_ENTRY',
				url: ''
			},
			{ id: 'DUGOUT_HOME_TEAM', name: 'DUGOUT_HOME_TEAM', url: '' },
			{ id: 'DUGOUT_AWAY_TEAM', name: 'DUGOUT_AWAY_TEAM', url: '' }
		];
		return json({ data: result });
	} catch (err) {
		console.error('Error fetching cameras:', err);
		throw error(500, 'Failed to fetch cameras');
	}
};
